export const INVESTOR_NDA_VERSION = "SBF-NDA-PORTAL-v3";

export const INVESTOR_NDA_CHECKBOX = "I have read and agree to the SBF WORLD Investor Portal Non Disclosure & Non Circumvention Agreement. I understand that by clicking “I Agree,” accessing the portal, or viewing any opportunity, I am entering into a legally binding agreement with Stogies, Birdies & Flights LLC d/b/a SBF WORLD.";

const articles = [
  ["1 — Definitions", "Opportunity includes any investment, asset, business, financing, acquisition, sale, partnership, development, joint venture, lease, hospitality project, real estate project, lending opportunity, equity opportunity, or future transaction involving a party introduced through SBF WORLD. Introduced Parties include every person or entity first identified, sourced, disclosed, or made available through SBF WORLD. Related Parties include the Recipient’s affiliates, owners, funds, portfolio companies, agents, representatives, nominees, intermediaries, and controlled entities. Confidential Information includes nonpublic identities, financials, underwriting, pro formas, models, valuations, pricing, terms, CIMs, LOIs, diligence, portal activity, sourcing, matching logic, routing, analytics, and all derivatives of that information."],
  ["2 — Purpose", "Confidential Information may be used solely to evaluate, pursue, or participate in an Opportunity through SBF WORLD. Permission to evaluate does not permit independent contact with transaction participants."],
  ["3 — Confidentiality", "The Recipient must keep Confidential Information strictly confidential, protect it with at least reasonable care, and use it only for the permitted purpose. Disclosure is limited to people with a legitimate need to know who are bound by obligations at least as protective as this Agreement. The Recipient remains responsible for their acts."],
  ["4 — Permitted Disclosures", "Permitted recipients are employees, officers, directors, affiliates, financing sources, investment committee members, legal counsel, accountants, consultants, and professional advisers who satisfy the confidentiality requirements. This Article controls over any conflicting interpretation of Article 5."],
  ["5 — Data Security & Unauthorized Use", "The Recipient may not copy, screenshot, scrape, download, forward, publish, post, upload, transfer, sell, distribute, or share Confidential Information; reverse engineer SBF WORLD underwriting, matching, routing, or analytics; create competing materials; contact an Introduced Party outside SBF WORLD; pursue an Opportunity outside SBF WORLD; or enable circumvention."],
  ["6 — Non Circumvention", "During portal access and for 24–36 months after the latest portal access, disclosure, or introduction, the Recipient may not directly or indirectly bypass, avoid, circumvent, interfere with, or exclude SBF WORLD from a transaction or relationship involving an Introduced Party. If substantive activity begins during that period, protection continues through closing or 12 months after the last substantive activity. A preexisting relationship must be disclosed in writing before contact and supported by documentary evidence of a material relationship independent of SBF WORLD."],
  ["7 — Introduced Parties", "Portal identity records, timestamps, access logs, opportunity IDs, communications, and downloads are contractually authoritative evidence of introduction, absent manifest error."],
  ["8 — Economic Consequences", "If circumvention results in a transaction that would reasonably have compensated SBF WORLD, the Recipient must pay the greater of the compensation SBF WORLD would have received or the specified percentage of gross transaction value, subject to applicable law."],
  ["9 — Return / Destruction", "On request, the Recipient must return, delete, or destroy Confidential Information, including notes, extracts, summaries, and derivative materials. Any archival copy remains protected."],
  ["10 — IP & Portal Rights", "Portal access is conditional and revocable and grants no ownership, license, exclusivity, or authority. SBF WORLD may suspend or revoke access at any time."],
  ["11 — Term & Survival", "Confidentiality survives for three years; trade-secret protection continues as long as legally protected; and non-circumvention survives for 24–36 months plus the applicable tail period."],
  ["12 — Remedies", "SBF WORLD may seek temporary, preliminary, and permanent injunctive relief, specific performance, damages, prevailing-party attorneys’ fees, costs, and all other remedies. Delay or failure to act is not a waiver."],
  ["13 — Governing Law & Arbitration", "North Carolina law applies. Disputes are subject to the Federal Arbitration Act and AAA Commercial Rules in Guilford County on an individual basis, with jury-trial and class-action waivers. SBF WORLD may seek emergency injunctive relief in North Carolina courts without waiving arbitration. International enforcement provisions apply."],
  ["14 — Electronic Acceptance", "Checkbox or clickwrap acceptance, account creation, portal login, document access, downloads, and continued portal use constitute binding acceptance. Portal records may include name, entity, title, email, IP address, timestamps, agreement version, immutable PDF hash, access logs, and downloads, and are authoritative evidence."],
  ["15 — No Obligation to Transact", "SBF WORLD is not obligated to provide opportunities, introduce parties, complete a transaction, or continue portal access."],
  ["16 — General", "This Agreement is the entire agreement, may be modified or assigned by SBF WORLD, may not be assigned by the Recipient without consent, and remains enforceable if a provision is narrowed."],
] as const;

export default function InvestorNdaAgreement() {
  return <div className="space-y-4 text-sm leading-6 text-chalk/75">
    <div className="rounded-2xl border border-gold/20 bg-gold/[.06] p-4">
      <div className="label-mono text-gold">Legally binding clickwrap agreement</div>
      <p className="mt-2">By clicking “I Agree,” creating an account, accessing the portal, viewing an opportunity, downloading a document, or continuing to use the portal, the Recipient agrees with Stogies, Birdies &amp; Flights LLC, doing business as SBF WORLD. A person acting for an entity represents that they have authority to bind it. Portal access and Confidential Information are sufficient consideration.</p>
    </div>
    {articles.map(([title, body]) => <section key={title}><h3 className="font-semibold text-chalk">Article {title}</h3><p className="mt-1">{body}</p></section>)}
  </div>;
}
