"use client";
import { useEffect, useState } from "react";
import Button from "@/components/ui/Button";
import Modal from "@/components/ui/Modal";
import { Icon } from "@/components/ui/Icons";
import { useSession } from "@/lib/session";
import type { BruceMatchDebug, BruceVisibleMatch } from "@/lib/bruceVisibleMatches";

export const compactBruceValue = (value: number) => !value ? "Not provided" : value >= 1e9 ? `$${(value/1e9).toFixed(1)}B` : value >= 1e6 ? `$${(value/1e6).toFixed(value >= 10e6 ? 0 : 1)}M` : `$${value.toLocaleString()}`;

export function useBruceVisibleMatches() {
  const { session } = useSession();
  const [matches, setMatches] = useState<BruceVisibleMatch[]>([]);
  const [visibleValue, setVisibleValue] = useState(0);
  const [debug, setDebug] = useState<BruceMatchDebug[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; const load = async () => { if (!session?.email) return; setLoading(true); try { const response = await fetch("/api/investor/bruce/matches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: "bruce@edenelevations3.com" }), cache: "no-store" }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error); if (!cancelled) { setMatches(payload.data.matches || []); setVisibleValue(payload.data.visibleValue || 0); setDebug(payload.data.debug || []); setError(""); } } catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : "Unable to load matches."); } finally { if (!cancelled) setLoading(false); } }; const refresh = () => { void load(); }; void load(); const timer = window.setInterval(refresh, 30000); window.addEventListener("focus", refresh); window.addEventListener("bruce-matches-updated", refresh); return () => { cancelled = true; window.clearInterval(timer); window.removeEventListener("focus", refresh); window.removeEventListener("bruce-matches-updated", refresh); }; }, [session?.email]);
  return { matches, visibleValue, debug, loading, error };
}

export function BruceMatchCards({ matches, limit }: { matches: BruceVisibleMatch[]; limit?: number }) {
  const [selected, setSelected] = useState<BruceVisibleMatch | null>(null);
  return <><div className="grid gap-5 lg:grid-cols-2 2xl:grid-cols-3">{matches.slice(0, limit || matches.length).map((match) => <article key={match.id} className="rounded-3xl border border-white/[.08] bg-gradient-to-br from-white/[.05] to-black/25 p-6 transition hover:-translate-y-1 hover:border-gold/40"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-[11px] text-emerald-300">{match.status}</span>{match.dataCleanupNeeded && <span className="rounded-full border border-amber-300/25 bg-amber-300/10 px-3 py-1 text-[11px] text-amber-200">Data Cleanup Needed</span>}</div><span className="text-sm font-semibold text-gold">{match.score ? `${match.score.replace(/%$/, "")}% match` : "Score pending"}</span></div><h3 className="mt-5 text-xl font-semibold text-chalk">{match.title}</h3><p className="mt-2 text-sm text-muted">{match.market || "Market not provided"} · {match.assetType || "Asset type not provided"}</p><div className="my-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="label-mono text-muted">Visible value</div><div className="mt-1 text-chalk">{match.valueLabel}</div></div><div className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="label-mono text-muted">Underwriting</div><div className="mt-1 truncate text-chalk">{match.underwritingStatus}</div></div></div><p className="line-clamp-3 text-xs leading-5 text-chalk/60">{match.teaser}</p><div className="mt-5 rounded-xl border border-gold/15 bg-gold/[.05] p-3 text-xs text-gold">Next: {match.nextStep}</div><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" onClick={() => setSelected(match)}>View Teaser</Button><Button size="sm" variant="outline">Show Interest</Button><Button size="sm" variant="ghost">Request Info</Button></div></article>)}</div><Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.title} sub="Approved teaser-safe match">{selected && <div className="space-y-4 text-sm text-chalk/70"><p className="leading-6">{selected.teaser}</p><div className="grid gap-3 sm:grid-cols-2">{[["Market", selected.market || "Not provided"],["Asset type",selected.assetType || "Not provided"],["Visible value",selected.valueLabel],["Match score",selected.score || "Not provided"],["Visibility",selected.visibility],["NDA",selected.ndaRequired]].map(([label,value])=><div key={label} className="rounded-xl border border-white/[.07] p-3"><div className="text-xs text-muted">{label}</div><div className="mt-1 text-chalk">{value}</div></div>)}</div><div className="rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-amber-100">NDA and qualification gate full underwriting, seller identity, raw financials, and asset-lock actions—not this approved teaser.</div></div>}</Modal></>;
}

export default function BruceMatchesPage() {
  const { matches, visibleValue, debug, loading, error } = useBruceVisibleMatches();
  return <div className="space-y-7 pb-10"><section className="rounded-[28px] border border-gold/20 bg-[radial-gradient(circle_at_85%_0%,rgba(212,175,55,.16),transparent_28rem),linear-gradient(135deg,rgba(255,255,255,.06),rgba(0,0,0,.3))] p-7"><div className="label-mono text-gold">Bruce Edwards · Approved teaser pipeline</div><h1 className="mt-3 text-3xl font-semibold text-chalk">Active Matches</h1><p className="mt-2 text-sm text-muted">Bruce-visible opportunities from God&apos;s Blueprint. Confidential details remain qualification-gated.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/[.08] bg-black/20 p-4"><div className="label-mono text-muted">Visible records</div><div className="mt-2 text-2xl text-chalk">{loading ? "…" : matches.length}</div></div><div className="rounded-2xl border border-white/[.08] bg-black/20 p-4"><div className="label-mono text-muted">Visible value</div><div className="mt-2 text-2xl text-gold">{loading ? "…" : compactBruceValue(visibleValue)}</div></div></div></section>{error && <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm text-amber-100">{error}</div>}{loading ? <div className="grid gap-4 lg:grid-cols-2">{[1,2,3,4].map(i=><div key={i} className="h-72 animate-pulse rounded-3xl bg-white/[.03]" />)}</div> : <BruceMatchCards matches={matches} />}{process.env.NODE_ENV === "development" && debug.length > 0 && <details className="rounded-2xl border border-white/[.08] bg-black/25 p-4 text-xs text-muted"><summary className="cursor-pointer text-gold">Development match inclusion debug ({debug.filter(x=>x.included).length} included / {debug.filter(x=>!x.included).length} excluded)</summary><div className="mt-3 space-y-2">{debug.map(item=><div key={item.id} className="rounded-lg border border-white/[.06] p-3"><span className={item.included?"text-emerald-300":"text-red-300"}>{item.included?"INCLUDED":"EXCLUDED"}</span> · <span className="text-chalk">{item.title}</span> — {item.reasons.join("; ")}</div>)}</div></details>}</div>;
}
