"use client";
import { useEffect, useMemo, useState } from "react";
import Button from "@/components/ui/Button";
import Modal from "@/components/ui/Modal";
import { Icon } from "@/components/ui/Icons";
import { useSession } from "@/lib/session";
import type { BruceScore } from "@/lib/bruceMatchingEngine";

type BuyBox = { id:string; title:string; status:string; investor:string; entity:string; assetClass:string; markets:string; priceRange:string; units:string; strategy:string; risk:string; returns:string; holdPeriod:string; requiredDocuments:string; notes:string; sourcePartner:string; updated:string };
const money = (value:number|null) => value ? `$${value>=1e6 ? `${(value/1e6).toFixed(value>=1e8?0:1)}MM` : value.toLocaleString()}` : "Not provided";

export default function BruceMatchingEngine({ embedded = false, onBuyBoxesLoaded }: { embedded?: boolean; onBuyBoxesLoaded?: (count: number) => void }) {
  const { session } = useSession();
  const [buyBoxes,setBuyBoxes]=useState<BuyBox[]>([]); const [selectedId,setSelectedId]=useState(""); const [records,setRecords]=useState<BruceScore[]>([]);
  const [loading,setLoading]=useState(false); const [started,setStarted]=useState(false); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All"); const [boxModal,setBoxModal]=useState<BuyBox|null>(null); const [assetModal,setAssetModal]=useState<BruceScore|null>(null); const [toast,setToast]=useState(""); const [appealing,setAppealing]=useState(""); const [requested,setRequested]=useState<Set<string>>(new Set());
  const [diagnostics,setDiagnostics]=useState<{portalsLoaded?:string[];allBuyBoxRows?:number;bruceBuyBoxRows?:number;candidateRows?:number;errors?:string[];sectionCounts?:Array<{email:string;sections:Record<string,number>}>}|null>(null);
  void requested;
  const run=async(id=selectedId)=>{setLoading(true);setError("");setStarted(true);try{const response=await fetch("/api/investor/bruce/matching-engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({buyBoxId:id}),cache:"no-store"});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.error);const loadedBuyBoxes=payload.data.buyBoxes||[];setBuyBoxes(loadedBuyBoxes);onBuyBoxesLoaded?.(loadedBuyBoxes.length);setRecords(payload.data.candidates||[]);setSelectedId(payload.data.selectedBuyBox?.id||id);setDiagnostics(payload.data.diagnostics||null);if(!loadedBuyBoxes.length&&!(payload.data.candidates||[]).length)setError("The Notion connection returned no live portal rows. Check that Buy Boxes & Mandates — CORE, Assets — CORE, Matching Engine — CORE, and Underwriting Engine — CORE are shared with the SBF WORLD integration and contain Brad or Bruce relationship fields.");}catch(e){setError(e instanceof Error?e.message:"Unable to run matching.");}finally{setLoading(false)}};
  useEffect(()=>{if(embedded)void run("");},[embedded]);
  const selectAndRun=(id:string)=>{setSelectedId(id);void run(id)};
  const appeal=async(asset:BruceScore)=>{setAppealing(asset.id);setToast("");try{const box=buyBoxes.find(item=>item.id===selectedId);const response=await fetch("/api/notion/portal/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:session?.email,submissionType:"matching",fields:{"Investor":"Bruce Edwards","Investor Entity":"Eden Elevations 3","Request":"Add to My Matches","Asset ID":asset.id,"Asset":asset.name,"Asset Type":asset.assetClass,"Price":asset.price?String(asset.price):"","Market":asset.market,"Match Score":String(asset.score),"Buy Box ID":box?.id||selectedId,"Buy Box":box?.title||"Selected mandate","Source Partner Lane":box?.sourcePartner||asset.partner,"Status":"Approved"}})});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.error);setRequested(current=>new Set(current).add(asset.id));window.dispatchEvent(new Event("bruce-matches-updated"));setToast(`${asset.name} was added to My Matches immediately.`);}catch(e){setToast(e instanceof Error?`Could not submit: ${e.message}`:"Could not submit match request.");}finally{setAppealing("")}};
  const shown=useMemo(()=>records.filter(row=>{const search=`${row.name} ${row.market} ${row.partner} ${row.underwritingStatus}`.toLowerCase().includes(query.toLowerCase());const category=filter==="All"||row.label===filter||(filter==="Blocked"&&row.blocked)||(filter==="Needs Docs"&&(!row.hasT12||!row.hasRentRoll));return search&&category}),[records,query,filter]);
  const selected=buyBoxes.find(item=>item.id===selectedId);
  return <div className={`space-y-8 ${embedded ? "pb-2" : "pb-10"}`}>
    <section className={`overflow-hidden border border-gold/20 bg-[radial-gradient(circle_at_88%_0%,rgba(212,175,55,.18),transparent_30rem),linear-gradient(135deg,rgba(255,255,255,.065),rgba(0,0,0,.34))] ${embedded ? "rounded-3xl p-6" : "rounded-[30px] p-7 sm:p-9"}`}><div className="label-mono text-gold">Bruce Edwards · Private Matching Engine</div><div className="mt-4 flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between"><div><h1 className={`${embedded ? "text-2xl" : "text-3xl sm:text-4xl"} font-semibold tracking-tight text-chalk`}>Run Bruce&apos;s buy boxes against all assets</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">Only Bruce Edwards and Eden Elevations 3 mandates appear here. Each mandate runs against the complete permitted SBF WORLD asset and underwriting pool, then ranks the strongest opportunities first.</p></div><div className="grid min-w-[360px] grid-cols-3 gap-2"><div className="rounded-2xl border border-white/[.08] bg-black/25 p-3 text-center"><div className="text-xl font-semibold text-chalk">{records.length||"—"}</div><div className="label-mono text-muted">Total assets</div></div><div className="rounded-2xl border border-white/[.08] bg-black/25 p-3 text-center"><div className="text-xl font-semibold text-gold">{started?shown.length:"—"}</div><div className="label-mono text-muted">Ranked results</div></div><div className="rounded-2xl border border-white/[.08] bg-black/25 p-3 text-center"><div className="text-xl font-semibold text-chalk">{buyBoxes.length||"—"}</div><div className="label-mono text-muted">Bruce buy boxes</div></div></div></div><div className="mt-7 border-t border-white/[.07] pt-6"><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><label><span className="label-mono text-gold">Bruce&apos;s live Notion buy box</span><select value={selectedId} onChange={event=>setSelectedId(event.target.value)} className="mt-2 w-full rounded-xl border border-gold/25 bg-[#0e0e0e] px-4 py-3 text-sm text-chalk outline-none focus:border-gold/60"><option value="">Choose Bruce&apos;s buy box…</option>{buyBoxes.map(box=><option key={box.id} value={box.id}>{box.title}</option>)}</select></label><Button size="lg" onClick={()=>selectedId?run(selectedId):run()} disabled={loading}>{loading?"Running Match…":selectedId?"Run Match":"Load Bruce Buy Boxes"}</Button></div>{selected&&<div className="mt-4 rounded-2xl border border-gold/15 bg-gold/[.04] p-4"><div className="font-medium text-chalk">{selected.title}</div><div className="mt-3 flex flex-wrap gap-2">{[["Asset class",selected.assetClass],["Geography",selected.markets],["Price",selected.priceRange],["Units",selected.units],["Strategy",selected.strategy]].map(([label,value])=><span key={label} className="rounded-full border border-white/[.08] bg-black/20 px-3 py-1.5 text-xs text-chalk/75"><span className="text-muted">{label}:</span> {value}</span>)}</div></div>}</div></section>
    {error&&<div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm text-amber-100">No alternate workspace data was used. {error}</div>}{toast&&<div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[.07] p-4 text-sm text-emerald-200">{toast}</div>}
    {!started?<section className={`rounded-3xl border border-dashed border-white/[.12] bg-white/[.02] text-center ${embedded ? "p-9" : "p-14"}`}><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gold/10 text-gold">{Icon.pulse(24)}</div><h2 className="mt-5 text-xl font-medium text-chalk">Bruce&apos;s mandates are ready to load.</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-muted">Load Bruce&apos;s private buy boxes, then run any mandate against every permitted candidate from God&apos;s Blueprint.</p></section>:<>
      <section><div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="label-mono text-gold">Step 1 · Bruce mandate library</div><h2 className="mt-2 text-2xl font-semibold text-chalk">My buy boxes</h2><p className="mt-1 text-sm text-muted">{buyBoxes.length} Bruce/Eden mandate{buyBoxes.length===1?"":"s"} fetched from Buy Boxes &amp; Mandates — CORE. Other investors&apos; buy boxes are excluded server-side.</p></div><span className={`rounded-full border px-3 py-2 text-xs ${buyBoxes.length||records.length?"border-emerald-400/20 bg-emerald-400/10 text-emerald-300":"border-amber-300/20 bg-amber-300/10 text-amber-200"}`}>{buyBoxes.length||records.length?"Live Notion data loaded":"No live rows returned"}</span></div>
      {loading&&!buyBoxes.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-64 animate-pulse rounded-3xl bg-white/[.03]"/>)}</div>:buyBoxes.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{buyBoxes.map(box=><article key={box.id} className={`rounded-3xl border p-5 transition ${selectedId===box.id?"border-gold/55 bg-gold/[.09] shadow-glow-sm":"border-white/[.08] bg-white/[.025] hover:border-gold/30"}`}><div className="flex items-center justify-between gap-3"><span className="rounded-full border border-white/[.09] px-2.5 py-1 text-[10px] text-muted">{box.status}</span>{selectedId===box.id&&<span className="text-xs text-gold">Selected ✓</span>}</div><h3 className="mt-4 line-clamp-2 text-lg font-semibold text-chalk">{box.title}</h3><p className="mt-2 text-xs text-muted">Bruce Edwards · Eden Elevations 3</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-black/20 p-3"><span className="text-muted">Asset class</span><div className="mt-1 truncate text-chalk">{box.assetClass}</div></div><div className="rounded-xl bg-black/20 p-3"><span className="text-muted">Strategy</span><div className="mt-1 truncate text-chalk">{box.strategy}</div></div><div className="rounded-xl bg-black/20 p-3"><span className="text-muted">Price</span><div className="mt-1 truncate text-chalk">{box.priceRange}</div></div><div className="rounded-xl bg-black/20 p-3"><span className="text-muted">Units</span><div className="mt-1 truncate text-chalk">{box.units}</div></div></div><div className="mt-4 flex gap-2"><Button size="sm" onClick={()=>selectAndRun(box.id)} disabled={loading}>{selectedId===box.id?"Run Matches Again":"Run Matches"}</Button><Button size="sm" variant="ghost" onClick={()=>setBoxModal(box)}>View Criteria</Button></div></article>)}</div>:<div className="rounded-3xl border border-dashed border-white/[.12] p-10 text-center text-sm text-muted">No Bruce/Eden buy-box records were returned. Confirm the Notion record contains “Bruce Edwards” or “Eden Elevations 3” in its investor, entity, title, related buy box, or criteria fields.</div>}</section>
      {selected&&<section className="rounded-3xl border border-gold/20 bg-gradient-to-r from-gold/[.10] to-transparent p-6"><div className="label-mono text-gold">Ranked match results</div><div className="mt-3 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold text-chalk">{selected.title}</h2><p className="mt-1 text-sm text-muted">Highest matching score appears first. Open any result to review the teaser and request addition to My Matches.</p></div><div className="rounded-xl border border-white/[.08] bg-black/25 px-5 py-3 text-center"><div className="text-2xl font-semibold text-gold">{shown.length}</div><div className="label-mono text-muted">Matches</div></div></div></section>}
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Buy boxes loaded",buyBoxes.length],["Candidates scanned",records.length],["Strong / good",records.filter(r=>r.score>=75).length],["Blocked / incomplete",records.filter(r=>r.blocked).length]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="label-mono text-muted">{label}</div><div className="mt-2 text-2xl text-chalk">{value}</div></div>)}</section>
      <section><div className="mb-4"><div className="label-mono text-gold">Step 3 · Matching output</div><h2 className="mt-2 text-2xl font-semibold text-chalk">All candidate data</h2><p className="mt-1 text-sm text-muted">Strong, partial, weak, and blocked records are all shown. Missing information is not silently removed.</p></div><div className="mb-5 flex flex-col gap-3 rounded-2xl border border-white/[.07] bg-white/[.02] p-4 xl:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-white/[.08] bg-black/30 px-3 text-muted">{Icon.search(16)}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search asset, market, partner, status…" className="w-full bg-transparent py-2.5 text-sm text-chalk outline-none"/></div><div className="flex gap-2 overflow-x-auto">{["All","Strong Match","Good Match","Possible Match","Blocked","Needs Docs"].map(item=><button key={item} onClick={()=>setFilter(item)} className={`whitespace-nowrap rounded-full border px-3 py-2 text-xs ${filter===item?"border-gold/50 bg-gold/15 text-gold":"border-white/[.08] text-muted"}`}>{item}</button>)}</div></div>
      {loading?<div className="grid gap-5 xl:grid-cols-2">{[1,2,3,4].map(i=><div key={i} className="h-72 animate-pulse rounded-3xl bg-white/[.03]"/>)}</div>:shown.length?<div className="grid gap-5 xl:grid-cols-2">{shown.map(row=><article key={row.id} className="rounded-3xl border border-white/[.08] bg-gradient-to-br from-white/[.05] to-black/25 p-6"><div className="flex items-start justify-between gap-4"><div><span className="text-xs text-muted">{row.market} · {row.partner}</span><h3 className="mt-2 text-xl font-semibold text-chalk">{row.name}</h3></div><div className="text-right"><div className={`text-2xl font-semibold ${row.score>=75?"text-emerald-300":row.score>=60?"text-gold":"text-amber-300"}`}>{row.score}</div><div className="text-[10px] text-muted">{row.label}</div></div></div><div className="my-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Price",money(row.price)],["Units",row.units||"Not provided"],["Asset type",row.assetClass||"Not provided"],["Underwriting",row.underwritingStatus]].map(([a,b])=><div key={a} className="rounded-xl bg-black/20 p-3"><div className="text-[10px] text-muted">{a}</div><div className="mt-1 truncate text-xs text-chalk">{b}</div></div>)}</div><div className="grid gap-4 sm:grid-cols-2"><div><div className="label-mono text-emerald-300">Why it fits</div><ul className="mt-2 space-y-1 text-xs leading-5 text-chalk/65">{row.strengths.slice(0,4).map(x=><li key={x}>✓ {x}</li>)}</ul></div><div><div className="label-mono text-amber-300">Missing / blockers</div><ul className="mt-2 space-y-1 text-xs leading-5 text-chalk/65">{row.blockers.slice(0,4).map(x=><li key={x}>• {x}</li>)}</ul></div></div><div className="mt-5 rounded-xl border border-gold/15 bg-gold/[.05] p-3 text-xs text-gold">Recommended: {row.nextAction}</div><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" onClick={()=>setAssetModal(row)}>View All Data</Button><Button size="sm" variant="outline" onClick={()=>appeal(row)} disabled={appealing===row.id}>{appealing===row.id?"Submitting…":"Request Add to My Matches"}</Button></div></article>)}</div>:<div className="rounded-3xl border border-dashed border-white/[.12] p-12 text-center text-sm text-muted">No candidates match this filter.</div>}</section>
    </>}
    {process.env.NODE_ENV==="development"&&diagnostics&&<details className="rounded-2xl border border-white/[.08] bg-black/30 p-4 text-xs text-muted"><summary className="cursor-pointer text-gold">Notion source diagnostics</summary><pre className="mt-3 overflow-x-auto whitespace-pre-wrap">{JSON.stringify(diagnostics,null,2)}</pre></details>}
    <Modal open={Boolean(boxModal)} onClose={()=>setBoxModal(null)} title={boxModal?.title} sub="Complete shared buy-box criteria" width="max-w-3xl">{boxModal&&<div className="grid gap-3 sm:grid-cols-2">{Object.entries(boxModal).filter(([key])=>key!=="id").map(([key,value])=><div key={key} className="rounded-xl border border-white/[.07] bg-white/[.025] p-4"><div className="text-xs capitalize text-muted">{key.replace(/([A-Z])/g," $1")}</div><div className="mt-1 whitespace-pre-wrap text-sm leading-6 text-chalk">{value||"Not provided"}</div></div>)}</div>}</Modal>
    <Modal open={Boolean(assetModal)} onClose={()=>setAssetModal(null)} title={assetModal?.name} sub="Complete teaser-safe candidate record" width="max-w-3xl">{assetModal&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2">{[["Market",assetModal.market],["State",assetModal.state],["Asset class",assetModal.assetClass],["Price",money(assetModal.price)],["Units",String(assetModal.units||"Not provided")],["Year built",String(assetModal.yearBuilt||"Not provided")],["Underwriting",assetModal.underwritingStatus],["Visibility",assetModal.visibility],["Partner",assetModal.partner],["Score",`${assetModal.score} · ${assetModal.label}`]].map(([a,b])=><div key={a} className="rounded-xl border border-white/[.07] p-4"><div className="text-xs text-muted">{a}</div><div className="mt-1 text-sm text-chalk">{b||"Not provided"}</div></div>)}</div><div className="rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm text-amber-100">This view shows all teaser-safe engine data. Seller identity, exact protected address, and raw financial documents remain access-controlled.</div></div>}</Modal>
  </div>;
}
