"use client";

type Row = { id: string; title: string; fields: Record<string, string> };
type Props = { records: Row[]; registryId: string; generatedAt: string };
const missing = "Not provided in 07 — Underwriting Engine — CORE";
const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

export default function FullUnderwritingPackage({ records, registryId, generatedAt }: Props) {
  const fields: Record<string, string> = Object.assign({}, ...records.map((row) => row.fields));
  const entries = Object.entries(fields);
  const get = (...names: string[]) => {
    const aliases = names.map(norm);
    const hit = entries.find(([key]) => aliases.includes(norm(key))) || entries.find(([key]) => aliases.some((name) => norm(key).includes(name)));
    return hit?.[1]?.trim() || missing;
  };
  const items = (...names: string[]) => get(...names) === missing ? [missing] : get(...names).split(/\r?\n|\s*[;•]\s*/).map((s) => s.replace(/^[-–—]\s*/, "").trim()).filter(Boolean);
  const Table = ({ heads = ["Field", "07 CORE Value"], rows }: { heads?: string[]; rows: string[][] }) => <div className="overflow-x-auto rounded-xl border border-white/[.09]"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-gold/[.09] text-gold"><tr>{heads.map((h) => <th key={h} className="px-3 py-3 uppercase tracking-wider">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={`${row[0]}-${i}`} className="border-t border-white/[.07]">{row.map((cell, j) => <td key={j} className={`whitespace-pre-wrap px-3 py-3 align-top ${j ? "text-chalk/80" : "font-medium text-muted"}`}>{cell}</td>)}</tr>)}</tbody></table></div>;
  const Section = ({ n, title, children }: { n: number; title: string; children: React.ReactNode }) => <section className="space-y-4 border-t border-gold/20 pt-6"><div className="label-mono text-gold">SECTION {n}</div><h3 className="text-xl font-semibold text-chalk">{title}</h3>{children}</section>;
  const List = ({ names }: { names: string[] }) => <ul className="space-y-2 pl-5 text-sm text-chalk/80">{items(...names).map((item, i) => <li key={i} className="list-disc marker:text-gold">{item}</li>)}</ul>;
  const pairs = (labels: string[]) => labels.map((label) => [label, get(label)]);
  const cards = (groups: Array<[string, string[]]>) => <div className="grid gap-4 md:grid-cols-3">{groups.map(([title, names]) => <div key={title} className="rounded-xl border border-white/[.08] p-4"><h4 className="mb-3 text-sm font-semibold text-gold">{title}</h4><List names={names} /></div>)}</div>;

  return <article className="space-y-8 rounded-2xl border border-gold/20 bg-[#0b0b09] p-5 sm:p-7">
    <header className="rounded-2xl border border-gold/25 bg-gradient-to-br from-gold/[.12] to-transparent p-6">
      <div className="label-mono text-gold">SBF WORLD · INSTITUTIONAL UNDERWRITING PACKAGE</div><div className="mt-2 text-[10px] uppercase tracking-[.25em] text-muted">Stogies · Birdies · Flights · Redefining Luxury Legacy</div>
      <h2 className="mt-6 text-3xl font-semibold text-chalk">{get("Asset Name", "Project Name", "Property Name")}</h2><p className="mt-2 text-sm text-muted">{get("Market", "Location Market")}</p><p className="mt-4 text-sm leading-6 text-chalk/75">{get("Program Summary", "Executive Summary", "Asset Summary")}</p>
      <div className="mt-6 grid gap-2 text-xs text-muted sm:grid-cols-3"><span>{registryId}</span><span>Full Underwriting Package</span><span>{new Date(generatedAt).toLocaleDateString()}</span></div><div className="mt-3 rounded-lg border border-emerald-400/20 bg-emerald-400/[.06] px-3 py-2 text-xs text-emerald-200">Live source: 07 — Underwriting Engine — CORE · {records.length} record(s)</div>
    </header>
    <Section n={1} title="Executive Underwriting Snapshot"><Table rows={pairs(["Asset", "Market", "Asset Type", "Strategy", "Site Area", "Zoning", "ASPR Approval", "Approved Residential", "Approved Hotel", "Approved Retail", "Total Entitled Units", "Affordable Housing", "Parking", "Open Space", "FAR", "Asking Price", "Vertical Development Estimate", "Target Construction Facility", "Estimated Debt", "Estimated Equity Requirement", "Buyer Role", "Match Score", "Source", "Oversight"])} /></Section>
    <Section n={2} title="Entitlement Analysis"><h4 className="text-sm font-semibold text-gold">ASPR Approval Summary</h4><Table rows={pairs(["Approval Reference", "Approval Date", "Approval Type", "Residential Component", "Hotel Component", "Retail Component", "Affordable Housing Condition", "Parking Provided", "Open Space Provided", "FAR Utilized", "Zoning"])} /><h4 className="text-sm font-semibold text-gold">Entitlement Conditions — Gating Items</h4><List names={["Entitlement Conditions", "Gating Items"]} /></Section>
    <Section n={3} title="Development Optionality Matrix"><Table heads={["Scenario", "Program", "Vertical Estimate", "Equity Required", "Notes"]} rows={["Current Approved Program", "Density Optimization", "Multifamily Only", "Hotel Removal", "Conservative Land Value", "Institutional Land Value", "Optimized Density Value"].map((name) => [name, get(`${name} Program`), get(`${name} Vertical Estimate`), get(`${name} Equity Required`), get(`${name} Notes`)])} /></Section>
    <Section n={4} title="Capital Stack Illustration"><Table rows={pairs(["Land Acquisition", "Hard Construction Costs", "Soft Costs / Fees", "Contingency", "Total Development Cost", "Target Construction Facility", "Lender Indication", "Estimated Debt", "Estimated Equity", "Buyer Role", "Vertical Estimate", "Development Spread"])} /><p className="text-xs italic text-muted">{get("Capital Stack Note", "Capital Stack Disclaimer")}</p></Section>
    <Section n={5} title="Market Overview"><p className="whitespace-pre-wrap text-sm leading-7 text-chalk/80">{get("Market Overview")}</p><h4 className="text-sm font-semibold text-gold">Demand Anchors</h4><List names={["Demand Anchors"]} /><h4 className="text-sm font-semibold text-gold">Affordable Housing Component</h4><p className="text-sm leading-7 text-chalk/80">{get("Affordable Housing Component")}</p></Section>
    <Section n={6} title="Comparable Transactions"><Table heads={["Comparable", "Location", "Program", "Sale Price", "Price / Unit", "Notes"]} rows={[1,2,3,4,5].map((n) => [get(`Comparable ${n}`), get(`Comparable ${n} Location`), get(`Comparable ${n} Program`), get(`Comparable ${n} Sale Price`), get(`Comparable ${n} Price Unit`), get(`Comparable ${n} Notes`)])} /><p className="text-sm text-chalk/80"><span className="text-gold">Observation: </span>{get("Comparable Observation")}</p></Section>
    <Section n={7} title="Technical Due Diligence Summary">{cards([["Environmental / Geotechnical", ["Environmental Geotechnical", "Environmental", "Geotechnical"]], ["Traffic / Concurrency", ["Traffic Concurrency"]], ["Utilities", ["Utilities"]]])}</Section>
    <Section n={8} title="Risk Register"><Table heads={["Risk", "Status", "Mitigation Required"]} rows={["Affordable Housing Covenant", "Construction Cost Escalation", "Hotel Feasibility", "FAR Optimization", "ASPR Conditions", "Aviation Determination", "Title / Ownership", "Seller Authority", "Lender Confirmation", "Buyer Paperwork"].map((name) => [name, get(`${name} Status`), get(`${name} Mitigation`)])} /></Section>
    <Section n={9} title="Diligence Checklist">{cards([["Transaction + Legal", ["Transaction Legal Checklist"]], ["Entitlement / Zoning / Approval File", ["Entitlement Zoning Approval Checklist"]], ["Technical Due Diligence", ["Technical Due Diligence Checklist"]], ["Underwriting Inputs", ["Underwriting Inputs Checklist"]]])}</Section>
    <Section n={10} title="Investor Match Analysis"><h4 className="text-sm font-semibold text-gold">{get("Investor Name", "Matched Investor", "Buyer Name")}</h4><Table heads={["Criteria", "Asset Alignment", "Status"]} rows={["Geography", "Asset Type", "Strategy", "Capital", "Timing", "Risk Profile"].map((name) => [name, get(`${name} Alignment`), get(`${name} Match Status`)])} /><Table rows={[["Overall Match Score", get("Overall Match Score", "Match Score")], ["Priority Status", get("Priority Status")]]} /></Section>
    <Section n={11} title="Recommended Next Actions">{cards([["Investor", ["Investor Next Actions"]], ["Source Partners", ["Source Partner Next Actions"]], ["SBF WORLD Oversight", ["Oversight Next Actions", "Recommended Next Actions"]]])}</Section>
    <footer className="border-t border-gold/20 pt-5 text-xs text-muted"><div className="text-gold">SBF WORLD · CONFIDENTIAL</div><div className="mt-2">{registryId} · Full Underwriting Package · {new Date(generatedAt).toLocaleDateString()}</div><div className="mt-2">All report values are populated exclusively from 07 — Underwriting Engine — CORE.</div></footer>
  </article>;
}
